# Generated by Django 2.2 on 2019-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='HKUST')),
                ('email', models.TextField(default='hkust@connect.ust.hk')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Albert')),
                ('email', models.TextField(default='albert@connect.us.hk')),
                ('password', models.IntegerField(default='123456')),
                ('product', models.TextField(default='egg')),
                ('origin', models.TextField(default='Taipei City')),
                ('certificate', models.TextField(default='SGS')),
                ('description', models.TextField(default='We have the best eggs')),
            ],
            options={
                'db_table': 'farmer',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(default='HKUST')),
                ('item', models.TextField(default='egg')),
                ('price', models.IntegerField(default=2)),
                ('quantity', models.IntegerField(default=1000)),
                ('farmer', models.TextField(default='Albert-Emily-')),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
